Enhance/unify error reporting and usage help

diff --git a/multipy b/multipy
--- a/multipy
+++ b/multipy
@@ -9,6 +9,16 @@ URL_TEMPLATE="http://www.python.org/ftp/python/%s/Python-%s.tgz"
 
 ### utils ###
 
+error() {
+    echo "Error: $1" >&2
+}
+
+die() {
+    [ -n "$1" ] && error "$1"
+    [ -n "$2" ] && echo "For logs, see $tempdir/*.log" >&2
+    exit 1
+}
+
 # Usage: append VAR STRING
 append() {
     eval local tmp=\$$1
@@ -34,7 +44,10 @@ is_supported_version() {
 get_version_args() {
     local version invalid
 
-    [ -n "$1" ] || die "No Python versions specified!"
+    if [ -z "$1" ]; then
+        error "No Python versions specified!"
+        return 1
+    fi
 
     if [ "$*" = "all" ]; then
         versions=$PYTHON_VERSIONS
@@ -46,7 +59,7 @@ get_version_args() {
         done
 
         if [ -n "$invalid" ]; then
-            echo "Invalid/unsupported Python version(s): $invalid" >&2
+            error "Invalid/unsupported Python version(s): $invalid"
             return 1
         fi
     fi
@@ -55,15 +68,19 @@ get_version_args() {
 # Assigns variables: version
 get_version_arg() {
     local v
-    [ -n "$1" ] || die "No Python version specified!"
+
+    if [ -z "$1" ]; then
+        error "No Python version specified!"
+        return 1
+    fi
 
     for v in $*; do
         if [ -n "$version" ]; then
-            echo "Single version expected" >&2
+            error "Single version expected"
             return 1
         fi
         if ! is_supported_version $v; then
-            echo "Invalid/unsupported Python version: $v" >&2
+            error "Invalid/unsupported Python version: $v"
             return 1
         fi
         version=$v
@@ -98,12 +115,6 @@ download_python() {
         fi
     done
     return 1
-}
-
-die() {
-    [ -n "$1" ] && echo "Error: $1" >&2
-    [ -n "$2" ] && echo "For logs, see $tempdir/*.log"
-    exit 1
 }
 
 
@@ -195,10 +206,10 @@ usage() {
 Usage: $0 [options] command [args...]
 
 Commands:
-    install [version...|all]
+    install version...|all
         Installs the given Python versions or all supported versions.
 
-    remove [version...|all]
+    remove version...|all
         Removes the given Python version or all installed versions.
 
     list
