Install setuptools instead of distribute

diff --git a/multipy b/multipy
--- a/multipy
+++ b/multipy
@@ -6,7 +6,7 @@
 
 PYTHON_VERSIONS="2.4 2.5 2.6 2.7 3.0 3.1 3.2 3.3"
 PYTHON_URL_TEMPLATE="http://www.python.org/ftp/python/%s/Python-%s.tgz"
-DISTRIBUTE_BASEURL="http://pypi.python.org/packages/source/d/distribute/"
+SETUPTOOLS_BASEURL="http://pypi.python.org/packages/source/s/setuptools/"
 
 # From virtualenv, with slight modifications
 ACTIVATE_SCRIPT=$(cat <<EOF
@@ -205,45 +205,45 @@ download_python() {
     return 1
 }
 
-# Assigns variables: latest_distribute
-install_distribute() {
+# Assigns variables: latest_setuptools
+install_setuptools() {
     local pyversion=$1
     local version versions tarball srcdir python
 
-    if [ -z "$latest_distribute" ]; then
-        echo "    Checking for latest version of distribute..."
+    if [ -z "$latest_setuptools" ]; then
+        echo "    Checking for latest version of setuptools..."
 
-        wget -q -O $tempdir/index.html $DISTRIBUTE_BASEURL || return 1
+        wget -q -O $tempdir/index.html $SETUPTOOLS_BASEURL || return 1
 
-        versions=$(grep -E '>distribute-[0-9.]+.tar.gz</a>' $tempdir/index.html | sed -r -e 's%.*>distribute-([0-9.]+).tar.gz</a>.*%\1%')
+        versions=$(grep -E '>setuptools-[0-9.]+.tar.gz</a>' $tempdir/index.html | sed -r -e 's%.*>setuptools-([0-9.]+).tar.gz</a>.*%\1%')
 
-        latest_distribute=0
+        latest_setuptools=0
         for version in $versions; do
-            if [ "$(version_cmp $version $latest_distribute)" -gt 0 ]; then
-                latest_distribute=$version
+            if [ "$(version_cmp $version $latest_setuptools)" -gt 0 ]; then
+                latest_setuptools=$version
             fi
         done
 
-        echo "    Found latest version: $latest_distribute"
+        echo "    Found latest version: $latest_setuptools"
 
-        tarball=distribute-$latest_distribute.tar.gz
+        tarball=setuptools-$latest_setuptools.tar.gz
         if [ ! -e "$tarball" ]; then
-            echo "    Downloading distribute..."
-            wget -q -P $sourcedir "$DISTRIBUTE_BASEURL/$tarball" || return 1
+            echo "    Downloading setuptools..."
+            wget -q -P $sourcedir "$SETUPTOOLS_BASEURL/$tarball" || return 1
         else
             echo "    $tarball already downloaded"
         fi
 
-        echo "    Unpacking distribute..."
+        echo "    Unpacking setuptools..."
         rm -rf $tempdir/$tarball
         gunzip -c $sourcedir/$tarball | tar -C $tempdir -xf - || return 1
     fi
 
-    echo "    Installing distribute..."
-    srcdir=$tempdir/distribute-$latest_distribute
+    echo "    Installing setuptools..."
+    srcdir=$tempdir/setuptools-$latest_setuptools
     python=$pythondir/$pyversion/bin/python$pyversion
     (cd $srcdir && $python setup.py install) \
-        > $tempdir/install-distribute.$pyversion.log 2>&1 \
+        > $tempdir/install-setuptools.$pyversion.log 2>&1 \
         || return 1
 }
 
@@ -287,8 +287,8 @@ install() {
             >$tempdir/install.$version.log 2>&1 \
             || die "Install failed" 1
 
-        if [ $no_distribute -eq 0 ]; then
-            install_distribute $version || die "Unable to install distribute" 1
+        if [ $no_setuptools -eq 0 ]; then
+            install_setuptools $version || die "Unable to install setuptools" 1
         fi
 
         # Write the activate script
@@ -379,7 +379,7 @@ Commands:
 Options:
     -b BASEDIR   The base directory [default: ~/multipy]
     -k           Keep temporary files and logs after installation
-    -n           Don't install distribute
+    -n           Don't install setuptools
     -j N         Compile with N jobs in parallel [default: $jobs_default]
 
 Upon startup, ~/.multipyrc and ~/.config/multipyrc are loaded. The
@@ -389,7 +389,8 @@ following variables can be assigned in these files:
 
     basedir=BASEDIR   -b BASEDIR
     keep_tmp=1        -k
-    no_distribute=1   -n
+    no_setuptools=1   -n
+    no_distribute=1   -n    (for backwards compatibility)
     jobs=2            -j 2
 
 Copyright (C) 2011-2014 Petri Lehtinen. Licenced under the MIT license.
@@ -399,7 +400,7 @@ EOF
 }
 
 basedir=$HOME/multipy
-no_distribute=0
+no_setuptools=0
 keep_tmp=0
 jobs_default=$(cpu_count)
 
@@ -408,13 +409,18 @@ jobs_default=$(cpu_count)
 [ -f $HOME/.multipyrc ] && . $HOME/.multipyrc
 [ -f $XDG_CONFIG_HOME/multipyrc ] && . $XDG_CONFIG_HOME/multipyrc
 
+# Backwards compatibility
+if [ -n "$no_distribute" ]; then
+    $no_setuptools=$no_distribute
+fi
+
 while getopts "b:knj:" opt; do
     case $opt in
         b)
             basedir=$OPTARG
             ;;
         n)
-            no_distribute=1
+            no_setuptools=1
             ;;
         k)
             keep_tmp=1
